name: workflow

on:
  push:
    branches:
      - main

jobs:
    job1:
        name: Ubuntu Time Check
        runs-on: ubuntu-latest
        steps:
        - name: Check Time
          run: date
    job2:
        name: Windows Time Check
        runs-on: windows-latest
        steps:
        - name: Check Time
          run: "Get-Date"
    job3:
        name: Mac OS Time Check
        runs-on: macos-latest
        steps:
        - name: Check Time
          run: date
    job4:
        needs: [job1, job2, job3]
        name: Ubuntu Uptime Check
        runs-on: ubuntu-latest
        steps:
        - name: Uptime
          run: uptime
